export const LOAD_USERS = "LOAD USERS";
export const LOAD_USERS_SUCCESS = "LOAD USERS SUCCESS";
export const LOAD_USERS_FAILURE = "LOAD USERS FAILURE";

export const USER_LOGIN = "USER LOGIN";
export const USER_LOGIN_SUCCESS = "USER LOGIN SUCCESS";
export const USER_LOGIN_FAILURE = "USER LOGIN FAILURE";
